### ISSUE TITLE
Need a minimal set of tasks defined for a valid build

### ISSUE THREAD

**Issue by peter-lamanna** [OpenPegasus/OpenPegasus#26]
The current "make build" does not build and output everything like the repository.  There are multiple steps requires to achieve the needed build output.  Also the "make tests" runs a suite of test cases of which only a few are really needed to validate a successful build.  What are the minimal set of tests and are they presently implemented in one of more Pegasus make targets?

**Comment by KSchopmeyer** [comment]
**DISCUSSION** I want to move this to next release

**Comment by KSchopmeyer** [comment]
Move to 2.14.4
