### ISSUE TITLE
Cannot build main branch on Ubuntu 18.04

### ISSUE THREAD

**Issue by dugganj** [OpenPegasus/OpenPegasus#35]
I get the following error:

mak/config.mak:51: /home/dugganj/OpenPegasus/env_var.status: No such file or directory
mak/config.mak:336: *** PEGASUS_PLATFORM environment variable must be set to one of the following:  .  Stop.

Attached is my environment variable settings .sh file.

(renamed .sh to .txt)
[pegvars_nossl_git.txt](https://github.com/KSchopmeyer/OpenPegasus/files/5482655/pegvars_nossl_git.txt)

**Comment by KSchopmeyer** [comment]
Issue resolved
