### ISSUE TITLE
Is it possible to configure cimserver on linux to *not* use OOP providers?

### ISSUE THREAD

**Issue by dugganj** [OpenPegasus/OpenPegasus#41]
It is possible to force all providers on the cimserver to use OOP providers using the forceExternalProvider option.  However, I have not found a way to configure the cimserver to *not* use OOP providers -- either using an option, or even with a compile-time define.

**Comment by KSchopmeyer** [comment]
Issue resolved

**Comment by KSchopmeyer** [comment]
Yes it is.  There is a build option PEGASUS_DEFAULT_ENABLE_OOP. If this is set to false, Providers are run in process.  The default is to run providers in OOP mode for Linux but in process for other platforms.

**Comment by KSchopmeyer** [comment]
I am closing this one as answered
